### ISSUE TITLE
Error when running NodeJS in Standalone mode, main script connection error

### ISSUE THREAD

**Issue by mightyt73** [getnamo/NodeJs-Unreal#53]
Hello!
I have been running into an issue trying to run this code in standalone mode in Unreal Engine. I am able to get the code working well in the Editor, but when running my application in Standalone the scripts do not seem to work. Is there anything I should look out for when trying to start the nodejs server in Standalone mode? or any suggestions on what I can look at to troubleshoot the issue.

Thanks!

![image](https://user-images.githubusercontent.com/68768245/233394512-466bd45a-63f8-4dd6-af02-4968bc7a16d6.png)

**Comment by mightyt73** [comment]
Actually might be non-issue. I tested with the editor closed, on just a packaged product and seemed to work. So maybe its something conflicting when I run standalone with editor open. I will investigate there. Packaged product did work for me.

**Comment by getnamo** [comment]
There are likely edge cases, I still consider this plugin an experimental one without robustness/stability expected out of something solid.

**Comment by mightyt73** [comment]
Yup I definitely understand. It has been very useful in my project. 

The only issue I run into is that the plugin seems to hang at times and prevents my scripts for working. If I go into task manager and kill the nodejs subprocesses, it is then recreated and works fine again.

Any chance you know a way to prevent this or why it might happen? If I go to task manager and stop/kill all the nodejs processes they are recreated and work again.

**Comment by getnamo** [comment]
Sounds like a missing cleanup call somewhere. If you can get me an accurate repro for what's needed to hang the process (and stop it from being cleaned up), I could look into making that path a bit more reliable

**Comment by mightyt73** [comment]
Will do. I will try to reproduce and make a new issue if so. Thank you!!
